baseurl = ""
title = "Hugo Roca"

theme = "hugo-coder"

languagecode = "es"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"
contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "docs"

[params]
    author = "Hugo Roca"
    description = "Este es mi sitio web personal"
    keywords = "developer,personal,software"
    info = "Consultor de Análisis y programación"
    avatarurl = "images/avatar.jpg"
    footercontent = ".Net, Java, PHP, Javascript, jQuery"

    hideCredits = false
    hideCopyright = false


    # Custom CSS
    custom_css = []

    # RTL support
    rtl = false

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/HugoRoca"
[[params.social]]
    name = "Facebook"
    weight = 2
    url = "https://www.facebook.com/huugooroca.Huugoo"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/hugoroca"

[[menu.main]]
    name = "Experiencia Laboral"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "Contacto"
    weight = 2
    url = "/about/"
